version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-n
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ndb
      MYSQL_USER: nuser
      MYSQL_PASSWORD: npass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
