spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ndb?useSSL=false&serverTimezone=UTC
    username: nuser
    password: npass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
clients:
  unsplash:
    base-url: "https://api.unsplash.com"
    search-path: "/search/photos"
    lang: "es"

  groq:
    base-url: "https://api.groq.com/openai/v1"
    completions-path: "/chat/completions"

  openrouter:
    base-url: "https://openrouter.ai/openai/v1"
    completions-path: "/chat/completions"
    token: "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"

  gemini:
    base-url: "https://generativelanguage.googleapis.com/v1beta"
    completions-path: "/models/gemini-2.5-flash:generateContent"
    token: "AIzaSyBND9gT9GrPJvQCCzWDqN0hQxcf2GaU4Dk"